version: "3.7"
services:
  todofy_nginx:
    container_name: todofy_nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - todofy_backend
      - todofy_frontend
  todofy_backend:
    container_name: todofy_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
  todofy_frontend:
    container_name: todofy_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
